### ISSUE TITLE
Password protecting private keys

### ISSUE THREAD

**Issue by lainieskate** [mathiasertl/django-ca#10]
Hi,

I tried password protect the private key for an intermediate CA by running:

`manage.py init_ca --pathlen=1 --parent=74:99:4C:CD:E1:35:40:B3:8D:58:5E:68:10:60:E0:94 --password=lainie_int_ca-5 lainie_int_ca-5 "/C=US/ST=MyState/L=MyCity/O=Org/CN=lainie_int_ca-5"`

And got this error:

`CommandError: Last argument must be string or callable`

It still created the Certificate Authority lainie_int_ca-5, but the private key file under `standalone/ca/files` was empty with file size 0.

Thanks for your help!

**Comment by mathiasertl** [comment]
password-protecting private keys is *finally* working correctly in django-ca 1.6.0.
