### ISSUE TITLE
REST api 

### ISSUE THREAD

**Issue by raydoom** [mathiasertl/django-ca#100]
Have a plan to support REST api?

**Comment by mathiasertl** [comment]
Hi!

I have thought about it, but i cannot really think of a use case so far.

If you want to retrieve certificates, it would be via ACME, everything else is usually a rather rare task.

Can you please describe what the use case is, and what you would like to do via that API?

Kr, mat

**Comment by raydoom** [comment]
My use case is to use CA as a certificate signing center to issue certificates to external systems. The main purpose is electronic signature rather than HTTPS. The electronic signature system uses REST API to request certificates from the CA system, mainly for internal system calls.

**Comment by mathiasertl** [comment]
Hi,

I can see the use case and I'm considering adding an optional API in the next release. Can you name the operations you'd need to perform via the API, and any details on what you would need there?

If it is an option for you, you can also run [from source](file:///home/mati/git/mati/django-ca/docs/build/html/quickstart_from_source.html) and add your own application that implements an API.

kr, Mat

**Comment by raydoom** [comment]
The follow
1，Certificate issuance
2，Certificate revocation
and the ejbca-ce support more
```
enroll
https://ejbca:443/ejbca/ejbca-rest-api/v1/certificate/pkcs10enroll
```

```
revoca
https://ejbca:443/ejbca/ejbca-rest-api/v1/certificate/UID=c-0ffptcqx8b7ci08t5,CN=ManagementCA,O=EJBCA Container Quickstart/2383db8d3057540d9ad80b0dff8e3180952acb60/revoca
```

**Comment by mathiasertl** [comment]
When issuing certificates, what features do you need? 

Have a look at the sign_cert command, there are plenty of options. Selecting the CA, the subject and expiry time seem obvious. I would also add the profile (server, client, ... and you can extend those). What about extensions and other fringe options?

Kr, mat

**Comment by raydoom** [comment]
Just convert  sign_cert command func to rest api, use json param provide the command-line params, like 
curl -X POST http://django-ca/api/sign_cert -d {ca:'32:BE:A9', alt:'example.com', csr:'example.csr'}
curl -X POST http://django-ca/api/sign_cert -d {alt:'IP:127.0.0.1'}
and so on ，I just think so

**Comment by mathiasertl** [comment]
Hi @raydoom!

The `feature/1.26.0-gh-100-api-draft` implements a first, but already pretty decent, draft for the API. I would mark this as still experimental at this point.

I will include it in the next release (which will be in two weeks or so). In the mean time, you can also try it out via docker compose by using the `mathiasertl/django-ca:gh-100` tag:

```
DJANGO_CA_VERSION=gh-100 docker compose up
```

You can then view the documentation at `https://example.com/django_ca/api/docs`.

**Comment by mathiasertl** [comment]
The experimental API is part of the latest release, `1.26.0`. It's further documented here: https://django-ca.readthedocs.io/en/latest/rest_api.html

Note that the endpoints are not considered stable, and may change in the next release - of course I welcome your input on this in new issues!

kr, Mat
