### ISSUE TITLE
Acme Disable new accounts

### ISSUE THREAD

**Issue by antt1995** [mathiasertl/django-ca#107]
Is their a way to stop new acme accounts from being made?

I want to create acme accounts on my servers and then Disable Acme account creation so I can leave Acme Working for certbot renew tasks.

**Comment by mathiasertl** [comment]
Hi, I'm working on the feature now, so this will be in 1.26.0!

**Comment by antt1995** [comment]
Thanks @mathiasertl

**Comment by mathiasertl** [comment]
I consider the feature completed, as I just merged this into main. I plan to release 1.26.0 by the end of August.
