### ISSUE TITLE
Generate private keys and CSR

### ISSUE THREAD

**Issue by xkill** [mathiasertl/django-ca#13]
django_ca does not support to generate CSR.

It could be useful to generate private keys, CSR and sign to create new certificates from the admin interface, command line or, at least, a method to do it.

**Comment by mathiasertl** [comment]
Sorry, but this is definitely deliberate. A good CA does not create private keys by itself and should **never** have access to the private key. Generate a private key and CSR where the key is used.

**Comment by dani** [comment]
This is an old and closed issue. But I have to disagree. Indeed, in theory, a good CA doesn't need, and shouldn't access the private keys. But in practice, most of the time, it's the same guy (or team) who both create the key/CSR and sign it by the CA. So it makes sens for a project like django-ca to optionally generate it

**Comment by mathiasertl** [comment]
No.

Generate the key on whatever system you're actually using it.
