### ISSUE TITLE
Add ability to resign certificates

### ISSUE THREAD

**Issue by mathiasertl** [mathiasertl/django-ca#19]
We have the CSR, so django-ca should be able to just resign certificates via webinterface or CLI.

**Comment by redNixon** [comment]
While planning for a new feature to allow cert generation and/or arbitrary CA's to have "approvers" for signing, this feature essentially came along for free.

Securely doing this(as well as hardening the current signing method) requires changes will break already deployed instances.  Without also pushing the next feature on my list at the same time("clustered" setups with more formalized trust segregation between the web, requester and signer parts), I can't think of a great way to generate private keys in a way that everyone would be happy with.

Based on the current structure and the ability to determine the authenticity of the subject data in the database, resigning seems too dangerous without having a human inspect the subject and key usage.

**Comment by mathiasertl** [comment]
possible since 1.10.0
