### ISSUE TITLE
Installation does not install static or template files

### ISSUE THREAD

**Issue by jcmcken** [mathiasertl/django-ca#2]
When I run an install either via ``pip`` or via a ``python setup.py install``, the ``ca/django_ca/static`` and ``ca/django_ca/templates`` directories are missing, causing parts of the admin site to fail to render.

I believe the source of the issue is that your ``setup.py:setup`` function doesn't define a ``package_data`` for non-Python distributable files (docs [here](https://docs.python.org/3/distutils/setupscript.html#installing-package-data)). The ``MANIFEST.in`` file only works for ``sdist`` (as documented [here](https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute)), hence only that command appears to work.

BTW, kudos, I like what you've done with this app!

**Comment by mathiasertl** [comment]
Thanks for the report - hopefully fixed by your merge!

**Comment by jcmcken** [comment]
I pulled down the 1.21 version you pushed up to PyPI and LGTM. Thanks!

**Comment by mathiasertl** [comment]
@jcmcken btw, I hope you've seen that 1.2 brings (experimental) OCSP support. I'm very proud of that ;-)
