### ISSUE TITLE
CSRs containing wildcard domains cannot be signed

### ISSUE THREAD

**Issue by redNixon** [mathiasertl/django-ca#24]
Signing a CSR that contains a wildcard DNS domain results in a ValueError exception thrown by utils.parse_general_name.  This is pretty much the same issue that Cryptography fixed awhile back(https://github.com/pyca/cryptography/issues/2054).

I've attached the traceback and a sample CSR with a wildcard CN for reference.

[traceback.txt](https://github.com/mathiasertl/django-ca/files/967396/traceback.txt)
[wildcard.csr.txt](https://github.com/mathiasertl/django-ca/files/967400/wildcard.csr.txt)

**Comment by mathiasertl** [comment]
Fixed in pull request
