### ISSUE TITLE
init_ca fails on Windows due to colons in key_path

### ISSUE THREAD

**Issue by sakurai-youhei** [mathiasertl/django-ca#28]
When I run `manage.py init_ca ...`, it results failure with following error message; Using colons in path is not allowed on Windows.

```
CommandError: [Errno 22] Invalid argument: 'C:\\Users\\sakurai\\Desktop\\test-ca\\files\\33:01:2C:1F:74:BC:7A:38:79:09:1D:CF:5B:B1:91:4A:30:83:E3:FF.key'
```

**Workaround**

Patch `django_ca.utils.add_colons` like this; It enables `manage.py init_ca ...` to pass without error at least.

```
from django_ca import utils
utils.add_colons = lambda s: s
```

**Comment by mathiasertl** [comment]
uch, Windows is such ja horrible system.

The workaround certainly works, *but* you should definetly disable the patch afterwards - the function is used in other parts of the system. I will work on a patch when I have time.

**Comment by mathiasertl** [comment]
Starting with the just-released 1.6.3, the colons are no longer included in the filenames, which should fix the issue.

**Comment by xbaro** [comment]
Version 1.10.0 use colons in key_path. Seems this issue was not closed.

**Comment by xbaro** [comment]
Is there any security reason to do not store the Key on the database? It can solve the colons problem and make this package easy to use in production, avoiding to require shared file systems.

**Comment by mathiasertl** [comment]
@xbaro shared filesystem between what?

At least on our system, we have a central database server, that django-ca also uses. I don't want my private keys there, as many systems have access that database server...

**Comment by mathiasertl** [comment]
... I am however open to a pull request that optionally stores the key in the database as well :-)
