### ISSUE TITLE
Add certificate property to check if the certificate is valid or not

### ISSUE THREAD

**Issue by xkill** [mathiasertl/django-ca#31]
Hi,

There is no easy way to check if a certificate is valid or not based on expiration date or revoked.

I suggest to add two properties:

"expired": like "revoked" but checking if the cert is expired or not
"valid": return true if not revoked or expired or false if expired or revoked.

**Comment by mathiasertl** [comment]
Hi!

Thanks for your suggestion. I'm not quite sure what area you are talking about. The Model class in the code? The command-line interface? The web interface?

**Comment by xkill** [comment]
The Model class.

* Certificate.revoked   # already implemented
* Certificate.expired:
```python
from datetime import datetime
def expired(self):
    return self.certificate.x509.not_valid_before > datetime.now()
```
* Certificate.valid:
```python
def valid(self):
    return self.revoked() or self.expired()
```

**Comment by mathiasertl** [comment]
The latter would mean the certificate is "valid" if it is either revoked or expired. Is that really what you want?

**Comment by xkill** [comment]
Yes.

**Comment by mathiasertl** [comment]
However, the opposite is true. A certificate is valid if it is neither revoked nor expired. Thus closing.
