### ISSUE TITLE
Apache Error 500

### ISSUE THREAD

**Issue by Techal62** [mathiasertl/django-ca#37]
Hello, I can not get the Django-ca web interface working, I still have a 500 error With apache under Ubuntu 18.04

<VirtualHost *:80>

        ServerName ca.example.com

        Alias /static/ /opt/django-ca/ca/static/

        WSGIDaemonProcess django_ca processes=1 python-path=/opt/django-ca/ca:/opt/django-ca/ca/ca:/opt/django-ca/lib/python2.7/site-packages threads=5
        WSGIProcessGroup django_ca
        WSGIApplicationGroup %{GLOBAL}
        WSGIScriptAlias / /opt/django-ca/ca/ca/wsgi.py

        <Directory /opt/django-ca/ca>
                <Files wsgi.py>
                        Require all granted
                </Files>
        </Directory>

        <Directory /opt/django-ca/ca/static>
                Require all granted
        </Directory>

</VirtualHost>

WSGIDaemonProcess django_ca processes=1 python-path =>

/opt/django-ca/lib/python2.7/site-packages => not found i have /opt/django-ca/lib/python3.6

**Comment by mathiasertl** [comment]
You will have to provide a little more information. Most importantly, check what your webserver logs say. And then google those error messages too ;-)
