### ISSUE TITLE
Allow hooking

### ISSUE THREAD

**Issue by amaccuish** [mathiasertl/django-ca#39]
I'd love somewhere where I could specify a script to run or an http endpoint to ping when a certificate is issued. My particular case is that I'd like certificates to be uploaded to our LDAP directory when they're issued.

**Comment by mathiasertl** [comment]
I've implemented a few signals to allow uses to hook into certain events:

http://django-ca.readthedocs.io/en/latest/signals.html

I hope this suits your needs?

**Comment by amaccuish** [comment]
Yes! Sorry I didn't see this! Closing :)
