### ISSUE TITLE
Enable user to download bundled certs

### ISSUE THREAD

**Issue by luflow** [mathiasertl/django-ca#52]
At the moment it's not possible to download a bundled cert which holds me back from using django-ca flawless out of the box.

I think it should be possible to retrieve a download from the cert list admin to retrieve a `cat`ed cert including the cert, the root ca and all intermediates.

I may have time in the next days to implement this as a PR.

Any additional thoughts?

**Comment by mathiasertl** [comment]
Great idea!

I'm open to a pull request.
