### ISSUE TITLE
Download of certificate in admin interface with strange naming

### ISSUE THREAD

**Issue by luflow** [mathiasertl/django-ca#53]
I just recognized that the file name of the certificates is not very intuitive. Maybe it would be better to have the common name as file name?

**Comment by mathiasertl** [comment]
You are right, the serial is not very intuitive. 

But I'm not really sure the Common Name is a good choice, either. Chrome and Firefox no longer support matching by CommonName. As far as I know, the Common Name is not a mandatory field.

**Comment by mathiasertl** [comment]
Turns out that #28 is relevant here too.

Unless someone opposes, I would use the common name and if it doesn't exist, use the first subjectAltName as filename.
