### ISSUE TITLE
Unknown OID causes a 500 error.

### ISSUE THREAD

**Issue by elfshed** [mathiasertl/django-ca#60]
When viewing imported certificates that were created with easy-rsa a 500 error is returned.

```
Unknown extension encountered: Unknown OID (2.16.840.1.113730.1.13)
```

This will probably also be the case with imported certificates created with xca's default settings since it pre-fills a *Netscape Comment* and provides an option to set a *Netscape Cert Type*.

**Comment by mathiasertl** [comment]
Hi @elfshed, thanks for the report!

Can you supply a certificate that triggers this error? That would be the easiest way for me to look at it and also include it in the test-suite.

**Comment by mathiasertl** [comment]
no comment from reporter, closing. If you see a similar issue, please report a new issue, of course.
