### ISSUE TITLE
Indicate to add 'django_object_actions' in INSTALLED_APPS in the doc

### ISSUE THREAD

**Issue by bruot** [mathiasertl/django-ca#63]
The [doc](https://django-ca.readthedocs.io/en/latest/install.html) says to add `django_ca` to the `INSTALLED_APPS`, but it does not mention `django_object_actions` although it must also be included. Maybe the doc could be more clear about this?

**Comment by mathiasertl** [comment]
You are absolutely right! Thank you for the report!

**Comment by mathiasertl** [comment]
I'm working through your issues right now, and will release this as 1.16.1.
