### ISSUE TITLE
ModuleNotFoundError: No module named 'django_ca.acme'

### ISSUE THREAD

**Issue by amotl** [mathiasertl/django-ca#67]
Dear Mathias,

first things first: Thanks a stack for conceiving and maintaining this excellent Python package.

We just gave the most recent version `django-ca-1.17.0` a spin and found that when invoking `python manage.py migrate` after having installed vanilla `django-ca`, it croaks like:
```
  File "/path/to/django_ca/models.py", line 60, in <module>
    from .acme.constants import BASE64_URL_ALPHABET
ModuleNotFoundError: No module named 'django_ca.acme'
```

Indeed, when looking inside the sdist package [1], you can verify the `acme` folder is missing.

With kind regards,
Andreas.

[1] https://files.pythonhosted.org/packages/5c/11/46f200ee04e19f28ba32ebb4f3856503f1742d984c991ee5f13bb981456c/django-ca-1.17.0.tar.gz

**Comment by mathiasertl** [comment]
Dear Andreas,

First I'm really annoyed that this issue (and that other one) did not show up in my github not notifications. So here I was happily continuing development, while I should have fixed packaging issues first. So apologies for the late reply. 

I'm sure you're right, I will release a fix as version 1.17.1 soon.

**Comment by mathiasertl** [comment]
> first things first: Thanks a stack for conceiving and maintaining this excellent Python package.

And thanks for the praise! :-)

**Comment by mathiasertl** [comment]
@amotl the CI test suite fixing these issues is currently running. If it passes, I will release 1.17.1 tomorrow (already making dinner for today, sorry ;-) )

If you like, you can also compare the branch with the fixes to release 1.17.0:

https://github.com/mathiasertl/django-ca/compare/1.17.0...bugfix/fix-1.17.0-packaging-issues

**Comment by amotl** [comment]
Dear Mathias,

> So here I was happily continuing development, while I should have fixed packaging issues first. So apologies for the late reply.

I saw that you have been really busy bringing more improvements to the code base and I appreciate that very much. No worries!

> I will release a fix as version 1.17.1 soon.

Thanks a stack. Don't hurry!

With kind regards,
Andreas.

**Comment by mathiasertl** [comment]
I just pushed release 1.17.1 to pypi and dockerhub.

The git tag is not yet pushed, as travis (or the django docs, I'm not sure) is currently having problems.

**Comment by amotl** [comment]
Hi Mathias,

thank you, I will test it on behalf of [tunfish-ca](https://github.com/tunfish/tunfish-ca) when I can find some time.

Regarding Travis CI, I hear you. Due to its recent restrictions on supporting FOSS projects, it is becoming more and more sluggish. I believe many people are migrating to GitHub Actions these days, as we are also doing just recently on behalf of e.g. https://github.com/crate/crate_ruby/pull/31 and https://github.com/crate/crate-dbal/pull/98. You might want to consider doing the same. Just let me know if you need some support on that.

With kind regards,
Andreas.
