### ISSUE TITLE
How to create an intermediate CA under a root CA

### ISSUE THREAD

**Issue by paulsimon99** [mathiasertl/django-ca#7]
Hi,

I'm able to create a root ca by init_ca, and try to create a hierarchy of CAs. Can you advise how to do that?

Thanks for comments

**Comment by mathiasertl** [comment]
This wasn't really explicitly documented so far, but I added a chapter [in the documentation](file:///home/mati/git/mati/django-ca/docs/build/html/ca_management.html#create-intermediate-cas) that I hope explains everything. Does that work for you?

**Comment by paulsimon99** [comment]
Thanks that works well 👍
