### ISSUE TITLE
TemplateDoesNotExist error

### ISSUE THREAD

**Issue by rebortg** [mathiasertl/django-ca#72]
Hi, when i want to add a new Cert via Admin Website a TemplateDoesNotExist is raised.

django_ca: 1.17.2 (via pip)
django: 3.1.7
python: 3.9

to reproduce:
1. start fresh django project with django_ca as `INSTALLED_APP`, migrate, collectstatic, createsuperuser.
2. create new ca via manage.py
3. try to add certs via Admin Webpage --> `TemplateDoesNotExist`

i notice, in my `$VENV_DIR/lib/python3.9/site-packages/django_ca` folder there is no `templates` folder.
After i manuell copied it from github it worked.

**Comment by mathiasertl** [comment]
Confirmed, thanks for the report!

**Comment by mathiasertl** [comment]
I plan to release the next version with the next week or two anyway. If you need a new point release until then, please let me know.

**Comment by rebortg** [comment]
no thx, i can wait for the release and in the mean time i can live with the workaround.

**Comment by amotl** [comment]
Hi Mathias,

we just upgraded to version 1.17.2 and have been hit by the same issue. If your time permits, it would be really nice to see a 1.17.3 release to mitigate that.

With kind regards,
Andreas.

cc @einsiedlerkrebs, @t-i-z

**Comment by mathiasertl** [comment]
I agree. Working on it.

**Comment by mathiasertl** [comment]
Just pushed 1.17.3 with test and fixes from this issue backported.

**Comment by amotl** [comment]
Dear Mathias,

thank you very much for this bugfix release. We just followed this on behalf of https://github.com/tunfish/tunfish-ca/commit/b665fd8102da59a1a00bfa5f35269dd6abf3d0dc and are able to confirm that the flaw described here has been mitigated.

Keep up the spirit and with kind regards,
Andreas.
