### ISSUE TITLE
The suggested way of making intermediate CA doesn't seem to work

### ISSUE THREAD

**Issue by paulsimon99** [mathiasertl/django-ca#8]
The suggested way to do intermediate CA at https://github.com/mathiasertl/django-ca/issues/7

doesn't seem to work after a closer look into the intermediate CA certs. 

Here is what I did:

[1] Generate root CA by: 
init_ca --pathlen=2 my_root_ca ...

[2] List the serial # of my root ca

[3] Generate intermediate CA by:

init_ca --pathlen=1 --parent='74:99:4C:CD:E1:35:40:B3:8D:58:5E:68:10:60:E0:94' my_server_ca "/C=US/ST=MyState/L=MyCity/O=Org/CN=my_server_ca"

The generate intermediate CA has the "issuer" equals itself, its own subject name, instead of the root ca. There might be a bug or I used it wrong?

Thanks for comments

**Comment by paulsimon99** [comment]
I think I fixed that in:

class CertificateAuthorityManager(models.Manager):
        .....
        if parent is None:
            authKeyId = crypto.X509Extension(b'authorityKeyIdentifier', False,
                                             b'keyid:always', issuer=cert)
        else:
            **# paul added
            cert.set_issuer(parent.x509.get_subject())**

            authKeyId = crypto.X509Extension(b'authorityKeyIdentifier', False,
                                             b'keyid,issuer', issuer=parent.x509)
...

Thanks for comments

**Comment by mathiasertl** [comment]
Hi,

I cannot reproduce this on my machine :-(, see the shell session below. I did find that the `fab init_demo` command did not actually pass a root CA to the child CA created there, but it doesn't seem to be what you have done.

Can you try the shell-session below and see what it turns up for you? You could also try in a fresh virtualenv with a new test-database. I'd of course also be interested in all relevant software info: OS, Python, OpenSSL, in a virtualenv? if yes: output of `pip freeze`? 


Here is what I did to try to reproduce this:

```
$ python manage.py init_ca --pathlen=2 my_root_ca "/CN=example.com"
$ python manage.py list_cas
3F:9A:4F:0C:D4:FE:40:55:95:40:BA:2D:59:A8:CF:D9 - my_root_ca
$ python manage.py init_ca --parent=3F:9A:4F:0C:D4:FE:40:55:95:40:BA:2D:59:A8:CF:D9 --pathlen=1 my_sub_ca "/CN=sub.example.com"
$ python manage.py list_cas
3F:9A:4F:0C:D4:FE:40:55:95:40:BA:2D:59:A8:CF:D9 - my_root_ca
7E:73:7B:DE:AD:0D:4B:E8:87:5D:97:1D:AE:1E:F1:68 - my_sub_ca
```

Now I dump the CA certs to a file:

```
$ python manage.py dump_ca 3F:9A:4F:0C:D4:FE:40:55:95:40:BA:2D:59:A8:CF:D9 > root.pem
$ python manage.py dump_ca 7E:73:7B:DE:AD:0D:4B:E8:87:5D:97:1D:AE:1E:F1:68 > child.pem
$ file *.pem
child.pem: PEM certificate
root.pem:  PEM certificate
```

... Now lets see, what `openssl x509` says - non-important parts stripped:

```
$ openssl x509 -in root.pem -noout -text
Certificate:
    Data:
        Serial Number:
            3f:9a:4f:0c:d4:fe:40:55:95:40:ba:2d:59:a8:cf:d9
    Signature Algorithm: sha512WithRSAEncryption
       X509v3 extensions:
            X509v3 Subject Key Identifier:   
                9A:BD:0A:0A:3D:5A:56:8A:D5:3E:35:58:8B:F4:39:9F:9D:83:60:9D
            X509v3 Authority Key Identifier: 
                keyid:9A:BD:0A:0A:3D:5A:56:8A:D5:3E:35:58:8B:F4:39:9F:9D:83:60:9D
```

... and the sub-ca:

```
$ openssl x509 -in child.pem -noout -text
Certificate:
    Data:
        Serial Number:
            7e:73:7b:de:ad:0d:4b:e8:87:5d:97:1d:ae:1e:f1:68
    Signature Algorithm: sha512WithRSAEncryption
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                FD:BF:D8:04:A4:C3:E6:15:F6:04:DF:0F:4D:FE:54:57:C9:E7:AE:A1
            X509v3 Authority Key Identifier:
                keyid:9A:BD:0A:0A:3D:5A:56:8A:D5:3E:35:58:8B:F4:39:9F:9D:83:60:9D
```

As you can see, the child-ca has an authKeyIdentifier referencing the parent CA...

**Comment by mathiasertl** [comment]
Oh wait - you mean the issuer. Hah! You're right of course! I didn't have this on my radar (or tested for it), because it wasn't one of the x509 extensions I so carefully documented.

**Comment by mathiasertl** [comment]
Thanks for the report. Do I get it correctly that you already generated a child-ca correctly? If yes, I'll wait a few days before releasing a new version, otherwise I can release one right away.

**Comment by paulsimon99** [comment]
After fixing that, I did generate child-ca and everything worked smoothly :)
