### ISSUE TITLE
ecc_curve in 'init_ca' command

### ISSUE THREAD

**Issue by bandirom** [mathiasertl/django-ca#84]
Python 3.10
Django_CA 1.20

Hi!)
I've updated django_ca to 1.20 and my some tests has been broken  :)
During the investigation I found some mismatch

![image](https://user-images.githubusercontent.com/46032838/154436884-4decc057-d9bd-43ce-9466-6831c561076a.png)

The issue is in the `ecc_curve`:

![image](https://user-images.githubusercontent.com/46032838/154437949-a19a367f-ebdb-446a-b149-9297bb3cf61b.png)

![image](https://user-images.githubusercontent.com/46032838/154438043-537a3dce-3e6d-4e1c-9e0f-0aec4b5d1307.png)

But when I commented this field, tests passed

**Comment by mathiasertl** [comment]
Hi @bandirom,

Thanks for the report!

There is a kind of hidden issue with yoru test case: Django itself says you should use `call_command()`, but in reality that skips the parsing of the argument parser. So when you call `manage.py init_ca ... --ecc-curve secp256r1`, the command function will actually receive an `ec.EllipticCurve` object, but with `call_command()` it won't. But we rely heavily on argparse parsing to parse strings into cryptography objects.

You have three options: 

1. Not test with an ECC curve as you did - probably not what you want.
2. Pass the  correct cryptography object.
3. Make use of the same, undocumented trick that we use: https://github.com/mathiasertl/django-ca/blob/main/ca/django_ca/tests/base/mixins.py#L606-L608

I think this should solve the issue for you?

kr, Mat

**Comment by mathiasertl** [comment]
PS: I have checked the default value (where it says `ABCMeta` in your screenshot) and verified that this only affects the output of the default value for  `--help`. The actual default value  is not wrong.

**Comment by mathiasertl** [comment]
closing this issue. If you need further assistance please reopen or create a new issue.

**Comment by bandirom** [comment]
Sorry, didnt have a time to reply. Im from Ukraine :) 
I will check when will be able :)  
Thank you!

**Comment by bandirom** [comment]
Hi!
I've fixed this bug.
for correct parsing need to provide values to call_command() as args not kwargs.

I mean the next one:
```python
args = [
      '--key-type', 'RSA',
      '--key-size', '4096',
      '--algorithm', 'sha512',
      '--expires', '3650',
]

call_command('init_ca', 'example', '/some/subject, *args)
```
and it will be handled properly :)
