### ISSUE TITLE
multiple SAN attributes not working

### ISSUE THREAD

**Issue by DonOtuseGH** [mathiasertl/django-ca#86]
Hello,

using the **django-ca cli** (latest docker image) i realised, that it's not possible to create certificates with multiple SAN attributes. Only the lastest `--alt` parameter value seems to be used:

`
$ manage sign_cert --alt www.example.com --alt wiki.example.com --csr certs/www.csr --out certs/www.pem
`

which results in a certificates with subject `CN=wiki.example.com `and `subjectAltName=DNS:wiki.example.com`. Could you please verify and solve this?

Thank you!

**Comment by mathiasertl** [comment]
Hi @DonOtuseGH ,

Thanks for your report (and for the other two), I'm checking on them now.

kr, Mat

**Comment by mathiasertl** [comment]
I've fixed the issue in main, the next release will include a fix. Thanks for your report!
