### ISSUE TITLE
Generate CT Certificate Transparency logs

### ISSUE THREAD

**Issue by westurner** [mathiasertl/django-ca#94]
- https://en.wikipedia.org/wiki/Certificate_Transparency
- https://en.wikipedia.org/wiki/Certificate_authority#Implementation_weakness_of_the_trusted_third_party_scheme
- https://www.google.com/m?q=certificate+Transparency+django
  - https://github.com/google/certificate-transparency/blob/master/python/ct/client/log_client.py
    - https://certificate.transparency.dev/
      - https://transparency.dev/verifiable-data-structures/
        - https://www.sigstore.dev/
          - https://github.com/topics/sigstore
          - https://github.com/blockchain-certificates/cert-issuer
            - https://github.com/blockchain-certificates/jsonld-signatures-merkleproof2019
            - https://github.com/digitalbazaar/jsonld-signatures#relationship-to-verifiable-credentials
              - https://github.com/digitalbazaar/vc-js#issuing-a-verifiable-credential
              - W3C DIDs https://en.wikipedia.org/wiki/Decentralized_identifier
                - https://www.w3.org/TR/did-core/
                  - peer DIDs https://github.com/decentralized-identity/peer-did-method-spec
                    - https://github.com/sicpa-dlab/peer-did-python#example
    - https://github.com/google/certificate-transparency-go/blob/master/client/ctclient/cmd/upload.go
    - https://github.com/google/certificate-transparency-go/blob/master/client/logclient.go
- https://github.com/google/trillian-examples
- https://github.com/topics/certificate-transparency
- https://django-ca.readthedocs.io/en/latest/ca_examples.html#precertificatesignedcertificatetimestamps
- .
- https://scholar.google.com/scholar?hl=en&as_sdt=0,10&q=%22Certificate+Transparency%22+blockchain&scisbd=1 by Relavancy / Date

**Comment by mathiasertl** [comment]
Hi,

I've waited here for a few days to see if anything comes from this. To be frank, posting a Wikipedia link and a bunch of random links including a Google search with no good results will typically not get anyone to do stuff that you would like to have implemented.

kr, Mat

**Comment by westurner** [comment]
Please pardon the free research. I wish you the best of luck with this project.
