### ISSUE TITLE
Profiles - default, custom and command line

### ISSUE THREAD

**Issue by doubledipped** [mathiasertl/django-ca#96]
I am running the latest release of django-ca using docker-compose and I have been able to create a new certificate profile using definitions set in a localsettings.yaml file.

However, I have run into some inter-related issues:

- I can't disable the 'webserver' profile - possibly because that is the default profile
- I can't set the default profile to be be the 'client' profile (using CA_DEFAULT_PROFILE: client), I was hoping to set this as default and then disable the webserver profile
- I am unable to select the client profile when using sign_cert from the command-line using the '--client' argument , it throws an error (see below). Using '--webserver' instead works however. Is the '--client' argument still supported?
- Is it possible to select other profiles including custom ones from the command-line, or do all the settings that make up a profile, need to be passed individually instead?

Error generated by using `docker-compose exec backend manage sign_cert --client ... <etc.>`

```
Traceback (most recent call last):
  File "/usr/local/bin/manage", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/src/django-ca/ca/django_ca/management/commands/sign_cert.py", line 123, in handle
    profile_obj = profiles[profile]
  File "/usr/src/django-ca/ca/django_ca/profiles.py", line 470, in __getitem__
    self._profiles.profiles[name] = get_profile(name)
  File "/usr/src/django-ca/ca/django_ca/profiles.py", line 450, in get_profile
    return Profile(name, **ca_settings.CA_PROFILES[name])
  File "/usr/src/django-ca/ca/django_ca/profiles.py", line 98, in __init__
    subject = Subject(subject)  # NOTE: also accepts None
  File "/usr/src/django-ca/ca/django_ca/subject.py", line 96, in __init__
    for oid, value in iterable:
ValueError: not enough values to unpack (expected 2, got 1)
```

Thanks

**Comment by mathiasertl** [comment]
(note: edited original post to fix syntax highlighting)

**Comment by mathiasertl** [comment]
Hi,

I cannot quite reproduce some of the issues that you report here. You write:

> * I can't disable the 'webserver' profile - possibly because that is the default profile
> * I can't set the default profile to be be the 'client' profile (using CA_DEFAULT_PROFILE: client), I was hoping to set this as default and then disable the webserver profile

When I use this YAML file:

```yaml
CA_DEFAULT_PROFILE: client
CA_PROFILES:
  webserver: null
```

I can successfully disable the `webserver` profile. This is evidenced by e.g. `manage.py sign_ca -h` no longer listing it in the section:

```
$ python manage.py sign_cert -h
...
profiles:
  Sign certificate based on the given profile. A profile only sets the the default values, options like --key-usage still override the profile.

  --client              A certificate for a client.
  --server              A certificate for a server, allows client and server authentication.
  --enduser             A certificate for an enduser, allows client authentication, code and email signing.
  --ocsp                A certificate for an OCSP responder.
```

However, I do see that just removing the webserver profile makes it unusable. I will add a check for that. In the meantime, the above setting will work just fine.

> I am unable to select the client profile when using sign_cert from the command-line using the '--client' argument , it throws an error (see below). Using '--webserver' instead works however. Is the '--client' argument still supported?

> I am unable to select the client profile when using sign_cert from the command-line using the '--client' argument , it throws an error (see below). Using '--webserver' instead works however. Is the '--client' argument still supported?

The traceback seems to be due to the question you posted in #95 - see the answer there! I will also add a check to better catch this error.

> Is it possible to select other profiles including custom ones from the command-line, or do all the settings that make up a profile, need to be passed individually instead?

Yes, that's possible - in fact it's the whole point of a profile! With the example I added [here](https://github.com/mathiasertl/django-ca/blob/feature/fix-93-95-96/docs/source/include/yaml-example-ca-profiles.yaml), `sign_cert` will show:

```
$ python manage.py sign_cert -h
profiles:
  Sign certificate based on the given profile. A profile only sets the the default values, options like --key-usage still override the profile.

  --client              A certificate for a client.
  --server              A certificate for a server, allows client and server authentication.
  --enduser             A certificate for an enduser, allows client authentication, code and email signing.
  --ocsp                A certificate for an OCSP responder.
  --new_profile         The description for the new profile
```

Please let me know if you have any further questions - or can't get some of this to work.

**Comment by doubledipped** [comment]
I think that the problems I was experiencing using profiles were consequences of the syntax format issue I was struggling with (#95) and having resolved that by following the examples you provided, I can now disable unrequired profiles and create ones without any problem. Thank you again for all your help

**Comment by mathiasertl** [comment]
Hi @doubledipped ,

Glad I could help you and I hope you like django-ca!

I added a check for if you specify a default profile that does not exist (whether that's because you removed it or you just have a typo) to help the next person that stumbles over that. The changes will be included in the next version of django-ca.

kr, Mat
